name: Compilar-Sistema-RG35XXH

on:
  push:
    branches: [ "main", "master", "principal" ]
  pull_request:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build-os:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout do Repositorio
      uses: actions/checkout@v4

    - name: Instalar Dependencias do Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential libncurses5-dev libssl-dev \
          sed make binutils g++ bash patch gzip bzip2 perl tar cpio \
          unzip rsync file bc wget git python3 python3-pip xz-utils

    - name: Baixar Projeto Customizado RG35XX H
      run: |
        # Clonando a árvore do Buildroot específica para consoles Allwinner H700
        git clone --depth 1 https://github.com/rg35xx-cfw/buildroot-rg35xx.git buildroot
        cd buildroot
        # Seleciona a configuração de fábrica para o modelo H
        make rg35xx_h_defconfig

    - name: Injetar Configuracoes Extras (WiFi, Bluetooth e Controles)
      run: |
        cd buildroot
        # Garante a ativação de drivers de rede e emulação básicos
        echo "BR2_PACKAGE_RTL8821CS=y" >> .config
        echo "BR2_PACKAGE_BLUEZ5_UTILS=y" >> .config
        echo "BR2_PACKAGE_WPA_SUPPLICANT=y" >> .config
        echo "BR2_PACKAGE_RETROARCH=y" >> .config
        make olddefconfig

    - name: Compilar Imagem (.img)
      run: |
        cd buildroot
        # Compila usando toda a força dos processadores do GitHub
        make -j$(nproc)

    - name: Enviar Imagem Pronta para Download
      uses: actions/upload-artifact@v4
      with:
        name: sistema-anbernic-windows-style
        path: buildroot/output/images/sdcard.img
        if-no-files-found: error
        retention-days: 7
